FROM quay.io/comp-bio-aging/bioperl:latest

LABEL maintainer="antonkulaga@gmail.com"

RUN apt-get update
# Install bioperl
RUN apt-get install -y bioperl

RUN git clone https://github.com/FelixKrueger/Sherman